# Generated by Django 5.2.5 on 2025-09-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_aianalysis_model_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnsembleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('majority_vote', 'Majority Vote'), ('average', 'Average'), ('weighted', 'Weighted'), ('stacking', 'Stacking')], max_length=50)),
                ('combined_prediction_label', models.CharField(choices=[('pneumonia', 'Pneumonia'), ('normal', 'Normal')], max_length=20)),
                ('combined_confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensemble_result', to='api.chestscan')),
            ],
        ),
        migrations.CreateModel(
            name='EnsembleResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0)),
                ('ensemble_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ensembleresult')),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelversion')),
            ],
        ),
        migrations.AddField(
            model_name='ensembleresult',
            name='models',
            field=models.ManyToManyField(related_name='ensemble_results', through='api.EnsembleResultModel', to='api.modelversion'),
        ),
    ]
