# Generated by Django 5.2.5 on 2025-09-01 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ensembleresult_ensembleresultmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensembleresult',
            name='models',
        ),
        migrations.AddField(
            model_name='ensembleresult',
            name='source_analyses',
            field=models.ManyToManyField(related_name='used_in_ensembles', to='api.aianalysis'),
        ),
        migrations.AlterField(
            model_name='ensembleresult',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ensemble_result', to='api.chestscan'),
        ),
        migrations.DeleteModel(
            name='EnsembleResultModel',
        ),
    ]
