# Generated by Django 5.2.5 on 2025-10-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_ensembleresult_models_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chestscan',
            name='final_label',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('pneumonia', 'Pneumonia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcase',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20),
        ),
    ]
