# Generated by Django 5.2.5 on 2025-10-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chestscan_final_label_alter_medicalcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chestscan',
            name='final_label_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
